# Generated by Django 4.0.4 on 2022-05-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('año', models.IntegerField()),
                ('nombreautor', models.CharField(max_length=40)),
                ('apellidoautor', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreusuario', models.CharField(max_length=40)),
                ('apellidousuario', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=40)),
                ('usuario', models.CharField(max_length=40)),
                ('clave', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vinilos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=40)),
                ('añovinilo', models.IntegerField()),
                ('nombrevinilo', models.CharField(max_length=40)),
                ('preciovinilo', models.IntegerField()),
            ],
        ),
    ]
