# Generated by Django 4.0.4 on 2022-07-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applibros', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuariomensaje', models.CharField(max_length=40)),
                ('comentario', models.CharField(max_length=40)),
            ],
        ),
    ]
